# Generated by Django 4.0.5 on 2022-07-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Car image'),
        ),
    ]
