# Generated by Django 4.0.5 on 2022-07-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_car_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moto',
        ),
    ]
